/* Database schema to keep the structure of entire database. */

CREATE TABLE animals(
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name varchar(40),
  date_of_birth date,
  escape_attemps INT NOT NULL,
  neutered boolean,
  weight_kg decimal(5, 2)
);

ALTER TABLE animals ADD species varchar(255);

/* Set the id as autoincremented and PRIMARY KEY */
ALTER TABLE animals ALTER COLUMN id  DROP IDENTITY IF EXISTS; /* Remove the default identity generation */
ALTER TABLE animals ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY; /* Add always identity generation */

/* Remove the 'species' column*/
ALTER TABLE animals DROP species;



/*------- CREATE THE 'owners' TABLE  -------*/
CREATE TABLE owners(
  id INT GENERATED ALWAYS AS IDENTITY,
  full_name varchar(255),
  age INT NOT NULL
);

/*------- CREATE THE 'species' TABLE  -------*/
CREATE TABLE species(
  id INT GENERATED ALWAYS AS IDENTITY,
  name varchar(255)
);

