/* Database schema to keep the structure of entire database. */

CREATE TABLE animals(
  id INT GENERATED BY DEFAULT AS IDENTITY,
  name varchar(40),
  date_of_birth date,
  escape_attemps INT NOT NULL,
  neutered boolean,
  weight_kg decimal(5, 2)
);

ALTER TABLE animals ADD species varchar(255);

/*------- CREATE THE 'owners' TABLE  -------*/
CREATE TABLE owners(
  id INT GENERATED ALWAYS AS IDENTITY,
  full_name varchar(255),
  age INT NOT NULL,
  PRIMARY KEY(id)
);

/*------- CREATE THE 'species' TABLE  -------*/
CREATE TABLE species(
  id INT GENERATED ALWAYS AS IDENTITY,
  name varchar(255),
  PRIMARY KEY(id)
);

